### ISSUE TITLE
Missing EnableQ2

### ISSUE THREAD

**Issue by fkhoda** [vmantek/chimera-demo#1]
Hi,

It seems that the EnableQ2 class is missing and as such the solution does not compile. Could you please add it?

Thanks..

**Comment by vsalaman** [comment]
Hi, sorry I had not updated the main chimera project. I have committed the latest changes. Although it is a snapshot version you can get a feel on how it works.

**Comment by fadil-khodabuccus-cko** [comment]
Thanks for this. However the demo is not compiling out of the box with the changes. Could you please look into it?

**Comment by vsalaman** [comment]
Can you try again?

**Comment by fadil-khodabuccus-cko** [comment]
I got this:

Could not resolve all files for configuration ':compileClasspath'.
> Could not find com.vmantek.chimera:chimera:1.0.5-SNAPSHOT.

**Comment by vsalaman** [comment]
Hi:

Since it's a snapshot, it's not published. Download chimera from
github:vmantek/chimera, and do "gradle install" and then the dependency
will be locally installed.


/V

**Comment by fadil-khodabuccus-cko** [comment]
Oh my bad.

Here you go:

Execution failed for task ':compileJava'.
> java.lang.ExceptionInInitializerError

**Comment by vsalaman** [comment]
Hi:

I have upgraded to Gradle wrapper to the latest version. Try it... btw,
I;ve only tested this with JDK 8

/V

**Comment by fadil-khodabuccus-cko** [comment]
Seems to be related to Lombok on JDK10. Upgrading it to 1.18.2 seems to resolve the compilation issue. Now I'm getting this on bootRun:

`org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.boot.InvalidMappingException: Could not parse mapping document: jar:file:/Users/fadil.khodabuccus/.gradle/caches/modules-2/files-2.1/org.jpos.ee/jposee-syslog/2.2.2/8d985d10c706c8b75f8e6cbf6469615934ee1312/jposee-syslog-2.2.2.jar!/org/jpos/ee/SysLog.hbm.xml (INPUT_STREAM)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1699) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	`

**Comment by vsalaman** [comment]
I doubr this works on JDK 10...

/V

**Comment by vsalaman** [comment]
I've upgraded some dependencies on the main project and the demo as well.
Hopefully it will work now on  your side.

**Comment by fadil-khodabuccus-cko** [comment]
Thanks a ton! It works but I had to remove "org.jpos.ee:jposee-syslog:2.2.2" from build.gradle since it was not running fine.

When it is included I got this:

```
2018-08-28 22:21:57.239  INFO 66453 --- [           main] com.vmantek.chimera.demo.Main            : No active profile set, falling back to default profiles: default
2018-08-28 22:21:57.296  INFO 66453 --- [           main] ConfigServletWebServerApplicationContext : Refreshing org.springframework.boot.web.servlet.context.AnnotationConfigServletWebServerApplicationContext@2141a12: startup date [Tue Aug 28 22:21:57 MUT 2018]; root of context hierarchy
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by org.springframework.cglib.core.ReflectUtils$1 (file:/Users/fadil.khodabuccus/.gradle/caches/modules-2/files-2.1/org.springframework/spring-core/5.0.8.RELEASE/dc39c49e3246cdf73d3786ac41119140aed3fa08/spring-core-5.0.8.RELEASE.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of org.springframework.cglib.core.ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
2018-08-28 22:21:59.122  INFO 66453 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$3817a175] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-08-28 22:21:59.163  INFO 66453 --- [           main] trationDelegate$BeanPostProcessorChecker : Bean 'org.springframework.hateoas.config.HateoasConfiguration' of type [org.springframework.hateoas.config.HateoasConfiguration$$EnhancerBySpringCGLIB$$b797eea7] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2018-08-28 22:21:59.615  INFO 66453 --- [           main] o.s.b.w.embedded.tomcat.TomcatWebServer  : Tomcat initialized with port(s): 8086 (http)
2018-08-28 22:21:59.644  INFO 66453 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2018-08-28 22:21:59.644  INFO 66453 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.32
2018-08-28 22:21:59.655  INFO 66453 --- [ost-startStop-1] o.a.catalina.core.AprLifecycleListener   : The APR based Apache Tomcat Native library which allows optimal performance in production environments was not found on the java.library.path: [/Users/fadil.khodabuccus/Library/Java/Extensions:/Library/Java/Extensions:/Network/Library/Java/Extensions:/System/Library/Java/Extensions:/usr/lib/java:.]
2018-08-28 22:21:59.797  INFO 66453 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2018-08-28 22:21:59.797  INFO 66453 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 2506 ms
2018-08-28 22:22:00.570  INFO 66453 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2018-08-28 22:22:00.571  INFO 66453 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'webMvcMetricsFilter' to: [/*]
2018-08-28 22:22:00.571  INFO 66453 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2018-08-28 22:22:00.571  INFO 66453 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2018-08-28 22:22:00.571  INFO 66453 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2018-08-28 22:22:00.571  INFO 66453 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpTraceFilter' to: [/*]
2018-08-28 22:22:00.571  INFO 66453 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Servlet dispatcherServlet mapped to [/]
2018-08-28 22:22:00.666  INFO 66453 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Starting...
2018-08-28 22:22:00.672  WARN 66453 --- [           main] com.zaxxer.hikari.util.DriverDataSource  : Registered driver with driverClassName=org.hsqldb.jdbcDriver was not found, trying direct instantiation.
2018-08-28 22:22:00.916  INFO 66453 --- [           main] com.zaxxer.hikari.pool.PoolBase          : HikariPool-1 - Driver does not support get/set network timeout for connections. (feature not supported)
2018-08-28 22:22:00.923  INFO 66453 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Start completed.
2018-08-28 22:22:01.021  INFO 66453 --- [           main] j.LocalContainerEntityManagerFactoryBean : Building JPA container EntityManagerFactory for persistence unit 'default'
2018-08-28 22:22:01.039  INFO 66453 --- [           main] o.hibernate.jpa.internal.util.LogHelper  : HHH000204: Processing PersistenceUnitInfo [
	name: default
	...]
2018-08-28 22:22:01.115  INFO 66453 --- [           main] org.hibernate.Version                    : HHH000412: Hibernate Core {5.2.17.Final}
2018-08-28 22:22:01.117  INFO 66453 --- [           main] org.hibernate.cfg.Environment            : HHH000206: hibernate.properties not found
2018-08-28 22:22:01.156  INFO 66453 --- [           main] o.hibernate.annotations.common.Version   : HCANN000001: Hibernate Commons Annotations {5.0.1.Final}
2018-08-28 22:22:01.396  WARN 66453 --- [           main] ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.boot.InvalidMappingException: Could not parse mapping document: jar:file:/Users/fadil.khodabuccus/.gradle/caches/modules-2/files-2.1/org.jpos.ee/jposee-syslog/2.2.2/8d985d10c706c8b75f8e6cbf6469615934ee1312/jposee-syslog-2.2.2.jar!/org/jpos/ee/SysLog.hbm.xml (INPUT_STREAM)
2018-08-28 22:22:01.396  INFO 66453 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown initiated...
2018-08-28 22:22:01.401  INFO 66453 --- [           main] com.zaxxer.hikari.HikariDataSource       : HikariPool-1 - Shutdown completed.
2018-08-28 22:22:01.404  INFO 66453 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2018-08-28 22:22:01.422  INFO 66453 --- [           main] ConditionEvaluationReportLoggingListener : 

Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-08-28 22:22:01.430 ERROR 66453 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'entityManagerFactory' defined in class path resource [org/springframework/boot/autoconfigure/orm/jpa/HibernateJpaConfiguration.class]: Invocation of init method failed; nested exception is org.hibernate.boot.InvalidMappingException: Could not parse mapping document: jar:file:/Users/fadil.khodabuccus/.gradle/caches/modules-2/files-2.1/org.jpos.ee/jposee-syslog/2.2.2/8d985d10c706c8b75f8e6cbf6469615934ee1312/jposee-syslog-2.2.2.jar!/org/jpos/ee/SysLog.hbm.xml (INPUT_STREAM)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1699) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:573) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:495) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:222) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1089) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:859) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550) ~[spring-context-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:762) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:398) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:330) ~[spring-boot-2.0.4.RELEASE.jar:2.0.4.RELEASE]
	at com.vmantek.chimera.JPosApplication.run(JPosApplication.java:42) [chimera-1.0.5-SNAPSHOT.jar:na]
	at com.vmantek.chimera.demo.Main.main(Main.java:17) [main/:na]
Caused by: org.hibernate.boot.InvalidMappingException: Could not parse mapping document: jar:file:/Users/fadil.khodabuccus/.gradle/caches/modules-2/files-2.1/org.jpos.ee/jposee-syslog/2.2.2/8d985d10c706c8b75f8e6cbf6469615934ee1312/jposee-syslog-2.2.2.jar!/org/jpos/ee/SysLog.hbm.xml (INPUT_STREAM)
	at org.hibernate.boot.jaxb.internal.InputStreamXmlSource.doBind(InputStreamXmlSource.java:46) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.boot.jaxb.internal.InputStreamXmlSource.doBind(InputStreamXmlSource.java:38) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.boot.spi.XmlMappingBinderAccess.bind(XmlMappingBinderAccess.java:79) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.boot.model.process.internal.ScanningCoordinator.applyScanResultsToManagedResources(ScanningCoordinator.java:219) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.boot.model.process.internal.ScanningCoordinator.coordinateScan(ScanningCoordinator.java:81) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.prepare(MetadataBuildingProcess.java:98) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:229) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.<init>(EntityManagerFactoryBuilderImpl.java:164) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider.createContainerEntityManagerFactory(SpringHibernateJpaPersistenceProvider.java:51) ~[spring-orm-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.createNativeEntityManagerFactory(LocalContainerEntityManagerFactoryBean.java:365) ~[spring-orm-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.buildNativeEntityManagerFactory(AbstractEntityManagerFactoryBean.java:390) ~[spring-orm-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.afterPropertiesSet(AbstractEntityManagerFactoryBean.java:377) ~[spring-orm-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean.afterPropertiesSet(LocalContainerEntityManagerFactoryBean.java:341) ~[spring-orm-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1758) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1695) ~[spring-beans-5.0.8.RELEASE.jar:5.0.8.RELEASE]
	... 15 common frames omitted
Caused by: org.hibernate.internal.util.config.ConfigurationException: Unable to build hbm.xml JAXBContext
	at org.hibernate.boot.jaxb.internal.MappingBinder.hbmJaxbContext(MappingBinder.java:84) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.boot.jaxb.internal.MappingBinder.doBind(MappingBinder.java:61) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.boot.jaxb.internal.AbstractBinder.doBind(AbstractBinder.java:102) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.boot.jaxb.internal.AbstractBinder.bind(AbstractBinder.java:57) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	at org.hibernate.boot.jaxb.internal.InputStreamXmlSource.doBind(InputStreamXmlSource.java:43) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	... 29 common frames omitted
Caused by: javax.xml.bind.JAXBException: Implementation of JAXB-API has not been found on module path or classpath.
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:278) ~[jaxb-api-2.3.0.jar:2.3.0]
	at javax.xml.bind.ContextFinder.find(ContextFinder.java:421) ~[jaxb-api-2.3.0.jar:2.3.0]
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:721) ~[jaxb-api-2.3.0.jar:2.3.0]
	at javax.xml.bind.JAXBContext.newInstance(JAXBContext.java:662) ~[jaxb-api-2.3.0.jar:2.3.0]
	at org.hibernate.boot.jaxb.internal.MappingBinder.hbmJaxbContext(MappingBinder.java:81) ~[hibernate-core-5.2.17.Final.jar:5.2.17.Final]
	... 33 common frames omitted
Caused by: java.lang.ClassNotFoundException: com.sun.xml.internal.bind.v2.ContextFactory
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582) ~[na:na]
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:190) ~[na:na]
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:499) ~[na:na]
	at javax.xml.bind.ServiceLoaderUtil.nullSafeLoadClass(ServiceLoaderUtil.java:122) ~[jaxb-api-2.3.0.jar:2.3.0]
	at javax.xml.bind.ServiceLoaderUtil.safeLoadClass(ServiceLoaderUtil.java:155) ~[jaxb-api-2.3.0.jar:2.3.0]
	at javax.xml.bind.ContextFinder.newInstance(ContextFinder.java:276) ~[jaxb-api-2.3.0.jar:2.3.0]
	... 37 common frames omitted
```

Do you have a clue?

Thanks..

**Comment by fadil-khodabuccus-cko** [comment]
Update: I had to add the following in build.gradle for it to run fine.

- compile 'javax.activation:activation:1.1.1'
- compile 'javax.xml.bind:jaxb-api:2.3.0'
- compile 'com.sun.xml.bind:jaxb-core:2.3.0'
- compile 'com.sun.xml.bind:jaxb-impl:2.3.0'

Thanks a lot!

Side question: Any plan to update to the latest Spring Boot 2.1? It seems that the EntityManagerFactoryBuilder.setCallback method that you used in JPosDatabaseAutoConfiguration is deprecated and removed from the Spring Boot 2.1 code base. Do you have any idea how to hook JPosPersistentUnitPostProcessor?

**Comment by vsalaman** [comment]
That's because the J2EE APIs have been removed in Java11. That's why they
are now part of the classpath on my last commit..l did you "gradle install"
on the main chimera project after updating?

/V

On Tue, Aug 28, 2018 at 2:26 PM, Fadil Khodabuccus <notifications@github.com

**Comment by fadil-khodabuccus-cko** [comment]
Sorry for late reply. Yes it is working fine now.  Thanks a lot!
